# -*- coding: utf-8 -*-
"""Huggingface.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1992ZEZdwfE1MwzVLq1G_PUhaVI-e1abd
"""

import time
import json
import requests

token_access="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"
headers={"Authorization": f"Bearer {token_access}"}

API_URL = "https://api-inference.huggingface.co/models/Helsinki-NLP/opus-mt-en-es"
def query(payload):
  data= json.dumps(payload)
  time.sleep(1)
  while True:
    try:
      response = requests.request("POST",API_URL,headers=headers, data=data)
      break
    except Exception:
      continue
  return json.loads(response.content.decode("utf-8"))
data = query({"inputs": "PragyanAI Is Data Science & AI Leading "})

data

data[0]["translation_text"]